sudo: required
services:
  - docker

before_install:
  - docker build -t cheehon/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cheehon/react-test npm test

after_success:
  - docker build -t cheehon/multi-client ./client
  - docker build -t cheehon/multi-nginx ./nginx
  - docker build -t cheehon/multi-server ./server
  - docker build -t cheehon/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push cheehon/multi-client
  - docker push cheehon/multi-nginx
  - docker push cheehon/multi-server
  - docker push cheehon/multi-worker
deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-1'
  app: 'complex-multi'
  env: 'Complexmulti-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-1-941993622343'
  buckey_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
